apiVersion: v1
kind: Service
metadata:
  name: task1-service
spec:
  type: ClusterIP
  selector:
    app: task1-app
  ports:
    - name: nginx-http
      port: 80
      targetPort: nginx-http
    - name: multitool-http
      port: 8080
      targetPort: multitool-http
